version = 0.1

[default.global.parameters]
stack_name = "personal-storage-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.deploy.parameters]
stack_name = "personal-storage-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = "Stage=dev"
